name: Repository Events
on:
  push:
    # branches and tags and paths need to all be matched
    branches:
      - main
      - 'feature/**' # matches feature/feata and feature/feata/featb
      - '!features/featc' # order matters, needs to be after feature/**
    # branches-ignore:  # can't use with branches
    #   - develop
    # tags:
    #   - v1.*
    #   - "!v1.1.1"
    paths:
      - '**.js'
      - '!ignore-me.js'
  pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
      - main
    paths:
      - '**.js'
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3
