name: Simple Javascript Action
on: [push]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Jeremy
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
